config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :users,
    controllers: {
      omniauth_callbacks: "users/omniauth_callbacks",
      sessions: "users/sessions",
      registrations: "users/registrations"
    }

  namespace :users do
    resources :settings, only: [ :edit, :update ]
    resources :events, except: [ :new, :edit ]
    resources :complete_registrations, only: [ :index, :update ]
  end

  resources :contacts, only: [ :create ]

  get 'home/index'
  root to: 'home#index'

  ##########################
  #         Themes         #
  ##########################
  resources :themes, only: :index do
    collection do
      %w(blank general buttons panels calendar gallery task_lists login basic_tables responsive_tables form_components).each do |action_name|
        get action_name
      end
    end
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  layout :resolve_layout
  expose(:active_calendar_link) { false }

  expose(:login_image_url) do
    System::GetAssetFilesUrls.get_image_url('theme/login-bg.jpg')
  end

  expose(:gallery_images_urls) do
    asset_matcher = 'app/assets/images/'
    path = asset_matcher + 'theme/portfolio/*.jpg'
    System::GetAssetFilesUrls.new(asset_matcher, path, 'images').run
  end

  def index
  end

  def blank
  end

  def general
  end

  def buttons
  end

  def panels
  end

  def calendar
  end

  def gallery
  end

  def task_lists
  end

  def login
  end

  def basic_tables
  end

  def responsive_tables
  end

  def form_components
  end

  private

  def resolve_layout
    case action_name
    when 'login'
      'theme_login'
    else
      'theme'
    end
  end
end

app/views/layouts/theme/_footer.html.slim
footer.site-footer
  .text-center
    | #{Time.now.year} - Ilgam Gaysin

app/views/layouts/theme/_header.html.slim
header.header.black-bg
  .sidebar-toggle-box
    .fa.fa-bars.tooltips[data-toggle="tooltip" data-placement="right" title="Toggle Navigation"]
  a.logo[href="#{root_path}"]
    b
      | WowCalendar
  #top_menu.nav.notify-row
    ul.nav.top-menu
      li.dropdown
        a.dropdown-toggle[data-toggle="dropdown" href="index.html#"]
          i.fa.fa-tasks
          span.badge.bg-theme
            | 4
        ul.dropdown-menu.extended.tasks-bar
          li
            p.green
              | You have 4 pending tasks
          li
            a[href="index.html#"]

              .task-info
                .desc
                  | DashGum Admin Panel
                .percent
                  | 40%
              .progress.progress-striped
                .progress-bar.progress-bar-success[role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%"]
                  span.sr-only
                    | 40% Complete (success)
          li
            a[href="index.html#"]

              .task-info
                .desc
                  | Database Update
                .percent
                  | 60%
              .progress.progress-striped
                .progress-bar.progress-bar-warning[role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%"]
                  span.sr-only
                    | 60% Complete (warning)
          li
            a[href="index.html#"]

              .task-info
                .desc
                  | Product Development
                .percent
                  | 80%
              .progress.progress-striped
                .progress-bar.progress-bar-info[role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%"]
                  span.sr-only
                    | 80% Complete
          li
            a[href="index.html#"]

              .task-info
                .desc
                  | Payments Sent
                .percent
                  | 70%
              .progress.progress-striped
                .progress-bar.progress-bar-danger[role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width: 70%"]
                  span.sr-only
                    | 70% Complete (Important)
          li.external
            a[href="#"]
              | See All Tasks
          .notify-arrow.notify-arrow-green

      li#header_inbox_bar.dropdown
        a.dropdown-toggle[data-toggle="dropdown" href="index.html#"]
          i.fa.fa-envelope-o
          span.badge.bg-theme
            | 5
        ul.dropdown-menu.extended.inbox
          li
            p.green
              | You have 5 new messages
          li
            a[href="index.html#"]
              span.photo
                = image_tag 'theme/ui-zac.jpg'
              span.subject
                span.from
                  | Zac Snider
                span.time
                  | Just now
              span.message
                |  Hi mate, how is everything?
          li
            a[href="index.html#"]
              span.photo
                = image_tag 'theme/ui-divya.jpg'
              span.subject
                span.from
                  | Divya Manian
                span.time
                  | 40 mins.
              span.message
                |  Hi, I need your help with this.
          li
            a[href="index.html#"]
              span.photo
                = image_tag 'theme/ui-danro.jpg'
              span.subject
                span.from
                  | Dan Rogers
                span.time
                  | 2 hrs.
              span.message
                |  Love your new Dashboard.
          li
            a[href="index.html#"]
              span.photo
                = image_tag 'theme/ui-sherman.jpg'
              span.subject
                span.from
                  | Dj Sherman
                span.time
                  | 4 hrs.
              span.message
                |  Please, answer asap.
          li
            a[href="index.html#"]
              | See all messages
          .notify-arrow.notify-arrow-green

  .top-menu
    ul.nav.pull-right.top-menu
      li
        = link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'logout'

app/views/layouts/theme/_sidebar.html.slim
aside
  #sidebar.nav-collapse
    ul#nav-accordion.sidebar-menu
      - if current_user.photo.present?
        p.centered
          a href="#{themes_path}"
            = image_tag current_user.photo.url(:thumb), class: 'img-circle', width: '60'
      h5.centered
        = current_user.decorate.provider_full_name

      li.mt
        a href="#{root_path}"
          i.fa.fa-home
          '
          span Главная

      li.sub-menu
        a href="#{users_events_path}" class="#{if active_calendar_link then 'active'}"
          i.fa.fa-calendar
          '
          span Календарь

      li.sub-menu
        a href="#{themes_path}" class="#{if !active_calendar_link then 'active'}"
          i.fa.fa-file
          '
          span Страницы из темы
        ul.sub
          li
            a href="#{general_themes_path}"  General
          li
            a href="#{buttons_themes_path}"  Buttons
          li
            a href="#{panels_themes_path}"  Panels
          li
            a href="#{calendar_themes_path}"  Calendar
          li
            a href="#{gallery_themes_path}"  Gallery
          li
            a href="#{task_lists_themes_path}"  Task List
          li
            a href="#{blank_themes_path}"  Blank Page
          li
            a href="#{login_themes_path}"  Login
          li
            a href="#{form_components_themes_path}"  Form Components
          li
            a href="#{basic_tables_themes_path}"  Basic Table
          li
            a href="#{responsive_tables_themes_path}"  Responsive Table